language: go
sudo: false
go:
  - 1.12.x
services:
  - docker
install: true
script:
  - chmod 777 -R "$(pwd)"
  - travis_retry make dep
  - make lint
  - make test
  - make integration
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -f .coverage/combined.cover.out
