version: '3'
services:
  test:
    image: asecurityteam/sdcli:v1
    environment:
      - "POSTGRES_URL=postgres://user:password@postgres/assetmgmt?sslmode=disable"
    command: go integration
    working_dir: ${DIR}
    volumes:
      - ${DIR}/db-migrations:/db-migrations
      - ${DIR}:${DIR}
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
      - "POSTGRES_DB=assetmgmt"
      - "PGDATA=/var/lib/postgresql/data/pgdata11"