// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asecurityteam/asset-inventory-api/pkg/domain (interfaces: StorageMigrator)

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageMigrator is a mock of StorageMigrator interface
type MockStorageMigrator struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMigratorMockRecorder
}

// MockStorageMigratorMockRecorder is the mock recorder for MockStorageMigrator
type MockStorageMigratorMockRecorder struct {
	mock *MockStorageMigrator
}

// NewMockStorageMigrator creates a new mock instance
func NewMockStorageMigrator(ctrl *gomock.Controller) *MockStorageMigrator {
	mock := &MockStorageMigrator{ctrl: ctrl}
	mock.recorder = &MockStorageMigratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorageMigrator) EXPECT() *MockStorageMigratorMockRecorder {
	return m.recorder
}

// Migrate mocks base method
func (m *MockStorageMigrator) Migrate(arg0 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate
func (mr *MockStorageMigratorMockRecorder) Migrate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockStorageMigrator)(nil).Migrate), arg0)
}

// Steps mocks base method
func (m *MockStorageMigrator) Steps(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Steps", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Steps indicates an expected call of Steps
func (mr *MockStorageMigratorMockRecorder) Steps(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Steps", reflect.TypeOf((*MockStorageMigrator)(nil).Steps), arg0)
}

// Version mocks base method
func (m *MockStorageMigrator) Version() (uint, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Version indicates an expected call of Version
func (mr *MockStorageMigratorMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockStorageMigrator)(nil).Version))
}
